name: dialog_alert_transition
description: "A new Flutter plugin project."
version: 0.0.3
homepage: mrNio.com
environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
